# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mysqldumpsplit < Formula
  desc "Split a mysqldump into separate files for each table."
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/afrase/mysqldumpsplit/releases/download/v0.1.1/mysqldumpsplit_Darwin_x86_64.tar.gz"
      sha256 "96ae695bc6a244a3a38f67e7bbc1be7c2b031419b34a75c3acef1bfa7934dfd1"

      def install
        bin.install "mysqldumpsplit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/afrase/mysqldumpsplit/releases/download/v0.1.1/mysqldumpsplit_Darwin_arm64.tar.gz"
      sha256 "c7f142707907bfa28aa80b6e2a167c4a3021f31864eaddb25e6a29eaace2ce97"

      def install
        bin.install "mysqldumpsplit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/afrase/mysqldumpsplit/releases/download/v0.1.1/mysqldumpsplit_Linux_x86_64.tar.gz"
      sha256 "7742088c2139819f3233f4c61a82bfcce744eaf98e059db1587c95246fa3f194"
      def install
        bin.install "mysqldumpsplit"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/afrase/mysqldumpsplit/releases/download/v0.1.1/mysqldumpsplit_Linux_armv6.tar.gz"
      sha256 "03131b9bf0c7941810104296b7118e8407e0939eed9aa9d916a0abbd6f297797"
      def install
        bin.install "mysqldumpsplit"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/afrase/mysqldumpsplit/releases/download/v0.1.1/mysqldumpsplit_Linux_arm64.tar.gz"
      sha256 "577d6169fbcfd7fa06272d38eaadee59c0db526b9420fe92566c831e80292f27"
      def install
        bin.install "mysqldumpsplit"
      end
    end
  end

  test do
    system "#{bin}/mysqldumpsplit -version"
  end
end
