# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Going < Formula
  desc "Simple CLI tool for working with AWS."
  homepage ""
  version "0.0.8"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/afrase/going/releases/download/v0.0.8/going_Darwin_arm64.tar.gz"
      sha256 "489c54ea586636fcfc811ead35b57d7721bfd9af89cfc6f51244c2bddef7f632"

      def install
        bin.install "going"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/afrase/going/releases/download/v0.0.8/going_Darwin_x86_64.tar.gz"
      sha256 "1f5d56afc87de1f9545f1e1d6bd85ff80afe50f46b53a24eccb2c1c088c68520"

      def install
        bin.install "going"
      end
    end
  end
end
