# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mysqldumpsplit < Formula
  desc "Split a mysqldump into separate files for each table."
  homepage ""
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/afrase/mysqldumpsplit/releases/download/v0.1.2/mysqldumpsplit_Darwin_x86_64.tar.gz"
      sha256 "8a5fe0b3dc2f8ee3594bb59e45884fe158b69f8312758bea42aa8d2e046353a1"

      def install
        bin.install "mysqldumpsplit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/afrase/mysqldumpsplit/releases/download/v0.1.2/mysqldumpsplit_Darwin_arm64.tar.gz"
      sha256 "af139f45bafea38a2b80489d8c546f1e60b06e727ba4efdcaf5ef8473496028d"

      def install
        bin.install "mysqldumpsplit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/afrase/mysqldumpsplit/releases/download/v0.1.2/mysqldumpsplit_Linux_x86_64.tar.gz"
      sha256 "246e014d1fbd5cd74f3c521f7a5fcc0365b01dff573f4a8162840ae961553e21"
      def install
        bin.install "mysqldumpsplit"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/afrase/mysqldumpsplit/releases/download/v0.1.2/mysqldumpsplit_Linux_armv6.tar.gz"
      sha256 "6b0d3027c5fae3be1aa0f540bf71445b62c8324ed52f21801505afd9387f5efc"
      def install
        bin.install "mysqldumpsplit"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/afrase/mysqldumpsplit/releases/download/v0.1.2/mysqldumpsplit_Linux_arm64.tar.gz"
      sha256 "9b7db6856f5a3ba1a6f5b9950b669858fbb8b7f93ebd45955cff9757901f12a7"
      def install
        bin.install "mysqldumpsplit"
      end
    end
  end

  test do
    system "#{bin}/mysqldumpsplit -version"
  end
end
